# Deep Learning
## Practical Deep Learning Tutorial with PyTorch - Tutorial N° 1

### 2021-2022

# 0. Presentation

PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer
vision and natural language processing, primarily developed by Facebook's AI Research lab (FAIR).
It is free and open-source software released under the Modified BSD license. Although the Python interface is 
more polished and the primary focus of development, PyTorch also has a C++ interface.

A number of pieces of Deep Learning software are built on top of PyTorch, including Tesla Autopilot,Uber's Pyro, 
HuggingFace's Transformers, PyTorch Lightning, and Catalyst.

PyTorch provides two high-level features:
    
    1. Tensor computing (like NumPy) with strong acceleration via graphics processing units (GPU) 
    
    2. Deep neural networks built on a tape-based automatic differentiation system 
 

# 1. Installation

<span style='color:green '> Anaconda : To install PyTorch via Anaconda, use the following conda command: </span>

<span style='color:blue '> Pip : To install PyTorch via pip, use the following command: </span>

Verification : To ensure that PyTorch was installed correctly, we can verify the installation by importing the torch module.

In [2]:
import torch

# 2. Tensors

<span style='color:green'>
At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a single number.
</span>

In [26]:
#Create a scalar (zero-dimensional tensor)
t0 = torch.tensor(2.)
t0

tensor(2.)

In [28]:
t0.shape

torch.Size([])

<span style='color:red'> 
"2." is a shorthand for 2.0. It is used to indicate to Python (and PyTorch) that you want to create a floating-point number. We can verify this by checking the dtype attribute of our tensor.
</span>

In [29]:
t0.dtype

torch.float32

<span style='color:green'> Let's try creating more complex tensors. </span>

### Vectors (1D Tensors)

In [44]:
#Create a vector (one-dimensional tensor)
t1 = torch.tensor([1., 2, 3, 4])
t1
print(t1.shape)

torch.Size([4])


In [51]:
# Print number of dimensions (1D) and size of tensor
print(f'dim: {t1.dim()}, size: {t1.size()[0]}')

dim: 1, size: 4


In [52]:
t2 = torch.Tensor([1, 0, 2, 0])
t2

tensor([1., 0., 2., 0.])

In [54]:
# Element-wise multiplication
t1 * t2

tensor([1., 0., 6., 0.])

In [56]:
# Scalar product
t1 @ t2

tensor(7.)

In [64]:
# In-place replacement of random number from 0 to 20
x = torch.Tensor(7).random_(20)
x

tensor([15., 13., 14.,  5., 13., 12., 13.])

In [65]:
print(f'first: {x[0]}, last: {x[-1]}')

first: 15.0, last: 13.0


In [73]:
# Extract sub-Tensor [from:to) 
x[1:3+1]

tensor([13., 14.,  5.])

In [80]:
# Create a tensor with integers ranging from 1 to 4, excluding 4
v = torch.arange(1, 4+1)
v

tensor([1, 2, 3, 4])

In [82]:
# Square all elements in the tensor
print(v.pow(2))

tensor([ 1,  4,  9, 16])


### Matrices (2D Tensors)

In [92]:
# Create a matrix (two-dimensional tensor) 2x4 tensor
m = torch.Tensor([[2, 5, 3, 7],
                  [4, 2, 1, 9]])
m

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [93]:
m.dim()

2

In [95]:
print(m.size(0), m.size(1), m.size(), sep=' -- ')


2 -- 4 -- torch.Size([2, 4])


In [96]:
# Returns the total number of elements, hence num-el (number of elements)
m.numel()

8

In [97]:
# Indexing row 0, column 2 (0-indexed)
m[0][2]

tensor(3.)

In [102]:
# Indexing row 0, column 2 (0-indexed)
m[0,2]

tensor(3.)

In [106]:
# Indexing column 1, all rows (returns size 2)
print(m[:, 1])
print(m[:, 1].size())

tensor([5., 2.])
torch.Size([2])


In [107]:
# Indexing column 1, all rows (returns size 2x1)
m[:, [1]]
print(m[:, [1]].size())

torch.Size([2, 1])


In [108]:
# Indexes row 0, all columns (returns 1x4)
m[[0], :]

tensor([[2., 5., 3., 7.]])

In [112]:
# Indexes row 0, all columns (returns size 4)
m[0, :]

tensor([2., 5., 3., 7.])

In [130]:
# Create tensor of numbers from 1 to 5 (excluding 5)
v = torch.arange(1., 4 + 1)
v

tensor([1., 2., 3., 4.])

In [134]:
m

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [131]:
m.shape

torch.Size([2, 4])

In [132]:
# Scalar product
m @ v

tensor([49., 47.])

In [136]:
# Calculated by 1*2 + 2*5 + 3*3 + 4*7
m[[0], :] @ v

tensor([49.])

In [118]:
# Calculated by 
m[[1], :] @ v

tensor([47.])

In [141]:
# Add a random tensor of size 2x4 to m
m + torch.rand(2, 4)

tensor([[2.4035, 5.1108, 3.5377, 7.0114],
        [4.9024, 2.1819, 1.2029, 9.2386]])

In [142]:
# Subtract a random tensor of size 2x4 to m
m - torch.rand(2, 4)

tensor([[1.6822, 4.2590, 2.4356, 6.8763],
        [3.4430, 1.2640, 0.3296, 8.0835]])

In [143]:
# Multiply a random tensor of size 2x4 to m
m * torch.rand(2, 4)

tensor([[1.4158, 4.8672, 2.0746, 6.9082],
        [2.5192, 1.4006, 0.8403, 5.8637]])

In [144]:
# Divide m by a random tensor of size 2x4
m / torch.rand(2, 4)

tensor([[ 2.2038, 17.7652,  8.7493,  9.3284],
        [79.0433,  3.7946,  2.3979, 95.7379]])

In [145]:
m.size()

torch.Size([2, 4])

In [146]:
# Transpose tensor m, which is essentially 2x4 to 4x2
m.t()

tensor([[2., 4.],
        [5., 2.],
        [3., 1.],
        [7., 9.]])

In [147]:
# Same as
m.transpose(0, 1)

tensor([[2., 4.],
        [5., 2.],
        [3., 1.],
        [7., 9.]])

### (3D Tensors)

<span style='color:green'>
Tensors can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the .shape property of a tensor.
</span>

In [162]:
#Create a 3-dimensional tensor
t3 = torch.tensor([[[11,12, 13,4],[13,14,15,58],[13,14,15,58]],[[15,16,17,56],[17,18,19.,0],[13, 14, 15,58]]])
t3

tensor([[[11., 12., 13.,  4.],
         [13., 14., 15., 58.],
         [13., 14., 15., 58.]],

        [[15., 16., 17., 56.],
         [17., 18., 19.,  0.],
         [13., 14., 15., 58.]]])

In [163]:
t3.dim()

3

In [164]:
t3.shape

torch.Size([2, 3, 4])

<span style='color:red '> Note that it's not possible to create tensors with an improper shape. </span>

In [184]:
# Matrix (2-dimensional tensor)
t4 = torch.tensor([[5., 6,11], 
                   [7, 8], 
                   [9, 10]])
t4

ValueError: expected sequence of length 3 at dim 1 (got 2)

<span style='color:red '> A ValueError is thrown because the lengths of the rows [5., 6, 11] and [7, 8] don't match. </span>

### More fun

In [185]:
# Creates two tensor of size 1x4
a = torch.Tensor([[1, 2, 3, 4]])
b = torch.Tensor([[5, 6, 7, 8]])
print(a.size(), b)

torch.Size([1, 4]) tensor([[5., 6., 7., 8.]])


In [189]:
# Concatenate on axis 0, so you get 2x4
torch.cat((a, b),0)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [190]:
# Concatenate on axis 1, so you get 1x8
torch.cat((a, b), 1)

tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])

# 3. Tensor operations and gradients

<span style='color:green'> We can combine tensors with the usual arithmetic operations. Let's look at an example: </span>

In [21]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

<span style='color:green'> We've created three tensors: x, w, and b, all numbers. w and b have an additional parameter requires_grad set to True. We'll see what it does in just a moment.
Let's create a new tensor y by combining these tensors. </span>

In [22]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, y is a tensor with the value 4 * 3 + 5 = 17. What makes PyTorch unique is that we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. This feature of PyTorch is called autograd (automatic gradients).

To compute the derivatives, we can invoke the .backward method on our result y.

In [23]:
# Compute derivatives
y.backward()

The derivatives of y with respect to the input tensors are stored in the .grad property of the respective tensors.



In [24]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


As expected, dy/dw has the same value as x, i.e., 3, and dy/db has the value 1. Note that x.grad is None because x doesn't have requires_grad set to True.

The "grad" in w.grad is short for gradient, which is another term for derivative. The term gradient is primarily used while dealing with vectors and matrices.

# 4.Tensor functions

Apart from arithmetic operations, the torch module also contains many functions for creating and manipulating tensors. Let's look at some examples.

In [25]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [26]:
# Create a tensor filled with the scalar value 0, with the shape defined by the variable argument size.
t10=torch.zeros(2, 3)
t10

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [28]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t2, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [29]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [31]:
# Change the shape of a tensor
t9 = t8.reshape(3, 2, 2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

In [32]:
# Create a a 2-D tensor with ones on the diagonal and zeros elsewhere.
t11=torch.eye(3)
t11

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [33]:
#Splits the tensor into chunks. Each chunk is a view of the original tensor.
torch.split(t11,1,1)

(tensor([[1.],
         [0.],
         [0.]]),
 tensor([[0.],
         [1.],
         [0.]]),
 tensor([[0.],
         [0.],
         [1.]]))

In [37]:
#Expects input to be <= 2-D tensor and transposes dimensions 0 and 1.0-D and 1-D tensors are returned as is.
#When input is a 2-D tensor this is equivalent to transpose(input, 0, 1).
t12 = torch.randn(2, 3)
print(t12)
t13=torch.t(t12)
t13

tensor([[ 0.7752, -0.1149,  1.8323],
        [ 0.2781,  0.3435, -0.7414]])


tensor([[ 0.7752,  0.2781],
        [-0.1149,  0.3435],
        [ 1.8323, -0.7414]])

In [38]:
#Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)[0,1)
torch.rand(4)

tensor([0.9717, 0.9576, 0.4566, 0.6577])

In [39]:
torch.rand(2, 3)

tensor([[0.1863, 0.8822, 0.4624],
        [0.8748, 0.1854, 0.8068]])

In [40]:
#Computes the absolute value of each element in input.
torch.abs(torch.tensor([-1, -2, 3]))

tensor([1, 2, 3])

In [41]:
#Adds the scalar other to each element of the input input and returns a new resulting tensor.
a = torch.rand(4)
print(a)
torch.add(a, 20)

tensor([0.5683, 0.5698, 0.5273, 0.1389])


tensor([20.5683, 20.5698, 20.5273, 20.1389])

In [42]:
#Computes the fractional portion of each element in input.
torch.frac(torch.tensor([1, 2.5, -3.2]))

tensor([ 0.0000,  0.5000, -0.2000])

In [44]:
#Returns a new tensor with the exponential of the elements of the input tensor input.
a = torch.rand(4)
torch.exp(torch.tensor([0, torch.log(torch.tensor(2.))]))

tensor([1., 2.])

You can learn more about tensor operations here: https://pytorch.org/docs/stable/torch.html . Experiment with some more tensor functions and operations using the empty cells below.

# 5. Interoperability with Numpy

Numpy is a popular open-source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays and has a vast ecosystem of supporting libraries, including:

Pandas for file I/O and data analysis

Matplotlib for plotting and visualization

OpenCV for image and video processing

Instead of reinventing the wheel, PyTorch interoperates well with Numpy to leverage its existing ecosystem of tools and libraries.

Here's how we create an array in Numpy:


In [45]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

We can convert a Numpy array to a PyTorch tensor using torch.from_numpy.

In [46]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

Let's verify that the numpy array and torch tensor have similar data types.

In [47]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert a PyTorch tensor to a Numpy array using the .numpy method of a tensor.

In [48]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

The interoperability between PyTorch and Numpy is essential because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

You might wonder why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data. There are two main reasons:

Autograd: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
GPU support: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.
We'll leverage both these features of PyTorch extensively in in the the coming sessions.